# Bibliotecas

In [36]:
import pandas as pd
import numpy as np

# Upload dados

In [37]:
olist_orders = pd.read_csv("../data/raw/olist_orders_dataset.csv")
olist_order_items = pd.read_csv("../data/raw/olist_order_items_dataset.csv")
olist_customers = pd.read_csv("../data/raw/olist_customers_dataset.csv")

In [38]:
olist_customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

# Processamento dos dados para o modelo

* Junção de tabelas
* Aplicação de filtros de variáveis
* Construção de features
    * Faturamento total por cliente
    * Quantidade total de pedidos por cliente

# Junção de tabelas

In [39]:
# informações dos clientes e seus respectivos pedidos
customers_orders = olist_customers.merge(olist_orders, how='inner', on='customer_id')
customers_orders.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05 00:00:00
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,2018-02-06 00:00:00
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,2018-06-13 00:00:00
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,2018-04-10 00:00:00
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,2018-08-09 20:55:48,2018-08-15 00:00:00

In [40]:
# informações dos itens desses pedidos
customers_orders_items = customers_orders.merge(olist_order_items, how='inner', on='order_id')
customers_orders_items.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05 00:00:00,1,a9516a079e37a9c9c36b9b78b10169e8,7c67e1448b00f6e969d365cea6b010ab,2017-05-22 15:22:12,124.99,21.88
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,2018-02-06 00:00:00,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-01-18 20:58:32,289.00,46.48
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,2018-06-13 00:00:00,1,bd07b66896d6f1494f5b86251848ced7,7c67e1448b00f6e969d365cea6b010ab,2018-06-05 16:19:10,139.94,17.79
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,2018-04-10 00:00:00,1,a5647c44af977b148e0a3a4751a09e2e,7c67e1448b00f6e969d365cea6b010ab,2018-03-27 16:31:16,149.94,23.36
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,2018-08-09 20:55:48,2018-08-15 00:00:00,1,9391a573abe00141c56e38d84d7d5b3b,4a3ca9315b744ce9f8e9374361493884,2018-07-31 10:10:09,230.00,22.25

# Filtro de variáveis

In [41]:
customers_orders_items.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state', 'order_id', 'order_status',
       'order_purchase_timestamp', 'order_approved_at',
       'order_delivered_carrier_date', 'order_delivered_customer_date',
       'order_estimated_delivery_date', 'order_item_id', 'product_id',
       'seller_id', 'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')

In [42]:
# seleção de colunas das variáveis
customers_orders_items = customers_orders_items.drop(columns=[
                                        i for i in customers_orders_items.columns if i not in ['customer_unique_id', 'order_id', 'order_status', 'price', 'freight_value' ]
])

customers_orders_items.columns

Index(['customer_unique_id', 'order_id', 'order_status', 'price',
       'freight_value'],
      dtype='object')

In [43]:
customers_orders_items.order_status.unique()

array(['delivered', 'invoiced', 'shipped', 'processing', 'canceled',
       'unavailable', 'approved'], dtype=object)

In [44]:
# retirando dados cancelados e invalidos
customers_orders_items = customers_orders_items[(customers_orders_items.order_status != 'canceled') & (customers_orders_items.order_status != 'unavailable')]

# Construção de Features - variáveis

## Faturamento total por cliente

In [45]:
customers_orders_items

,customer_unique_id,order_id,order_status,price,freight_value
0,861eff4711a542e4b93843c6dd7febb0,00e7ee1b050b8499577073aeb2a297a1,delivered,124.99,21.88
1,290c77bc529b7ac935b93aa66c333dc3,29150127e6685892b6eab3eec79f59c7,delivered,289.00,46.48
2,060e732b5b29e8181a18229c7b0b2b5e,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,139.94,17.79
3,259dac757896d24d7702b9acbbff3f3c,951670f92359f4fe4a63112aa7306eba,delivered,149.94,23.36
4,345ecd01c38d18a9036ed96c73b8d066,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,230.00,22.25
...,...,...,...,...,...
112645,1a29b476fee25c95fbafc67c5ac95cf8,6760e20addcf0121e9d58f2f1ff14298,delivered,74.90,13.88
112646,d52a67c98be1cf6a5c84435bd38d095d,9ec0c8947d973db4f4e8dcf1fbfa8f1b,delivered,114.90,14.16
112647,e9f50caf99f032f0bf3c55141f019d99,fed4434add09a6f332ea398efd656a5c,delivered,37.00,19.04
112648,73c2643a0a458b49f58cea58833b192e,e31ec91cea1ecf97797787471f98a8c2,delivered,689.00,22.07
112649,84732c5050c01db9b23e19ba39899398,28db69209a75e59f20ccbb5c36a20b90,delivered,13.99,7.78

In [46]:
values_by_customer = customers_orders_items.groupby(by='customer_unique_id').sum(numeric_only=True)

In [47]:
values_by_customer['total_value'] = values_by_customer['price'] + values_by_customer['freight_value']

In [48]:
values_by_customer.describe()

              price  freight_value   total_value
count  94983.000000   94983.000000  94983.000000
mean     142.071747      23.595025    165.666772
std      216.074999      22.867488    226.726478
min        0.850000       0.000000      9.590000
25%       47.900000      14.090000     63.100000
50%       89.890000      17.600000    107.900000
75%      155.000000      25.540000    182.930000
max    13440.000000    1794.960000  13664.080000

## Quantidade total de pedidos por cliente

In [50]:
# retirando dados 
customers_orders = customers_orders[(customers_orders.order_status != 'canceled') & (customers_orders.order_status != 'unavailable') & (customers_orders.order_status != 'created')]

In [56]:
#agrupando os itens por cliente e resetando o index
quant_orders_by_cust = customers_orders.groupby(by='customer_unique_id').count()['order_id']
quant_orders_by_cust = quant_orders_by_cust.reset_index(level=0)

In [55]:
values_by_customer = values_by_customer.reset_index(level=0)

In [59]:
# junção das informações
customers_info = values_by_customer.merge(quant_orders_by_cust, how='inner', on='customer_unique_id')

In [ ]:
customers_info = customers_info.drop(columns=['price','freight_value'])
customers_info = customers_info.rename(columns={'order_id':'quant_orders'})

In [66]:
customers_info

                     customer_unique_id  total_value  quant_orders
0      0000366f3b9a7992bf8c76cfdf3221e2       141.90             1
1      0000b849f77a49e4a4ce2b2a4ca5be3f        27.19             1
2      0000f46a3911fa3c0805444483337064        86.22             1
3      0000f6ccb0745a6a4b88665a16c9f078        43.62             1
4      0004aac84e0df4da2b147fca70cf8255       196.89             1
...                                 ...          ...           ...
94978  fffcf5a5ff07b0908bd4e2dbc735a684      2067.42             1
94979  fffea47cd6d3cc0a88bd621562a9d061        84.58             1
94980  ffff371b4d645b6ecea244b27531430a       112.46             1
94981  ffff5962728ec6157033ef9805bacc48       133.69             1
94982  ffffd2657e2aad2907e67c3e9daecbeb        71.56             1

[94983 rows x 3 columns]

In [67]:
customers_info.describe()

        total_value  quant_orders
count  94983.000000  94983.000000
mean     165.666772      1.033859
std      226.726478      0.210811
min        9.590000      1.000000
25%       63.100000      1.000000
50%      107.900000      1.000000
75%      182.930000      1.000000
max    13664.080000     16.000000

In [71]:
customers_info.to_csv("../data/customers_info.csv")